server.error.whitelabel.enabled: true
server:
    port: 8080
    connection-timeout: 30000
registerApiConfig:                                                     
    request:
        timeout: 30000
    rest:
        connectionTimeout: 10000
        readTimeout: 10000
    failsafe:
        failureRateThreshold: 10
        waitDurationInOpenState: 1000
        slidingWindowSize: 2             
        timeoutDuration: 5
        
logging:
    file: magicApi.log

info:
    app:
        name: Register API
        description: Desafio Teste
        version: @project.version@
        profile: desenvolvimento

swagger:
    title: Register API
    description: Desafio Teste
    version: @project.version@
    termsOfServiceUrl:
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
    protocol: http
